map_name: mc_medieval_3_teams
default_spawn:
  x: 83
  y: 55
  z: -4
arena:
  chest:
    x: 83.0
    y: 55.0
    z: -4.0
  teleport:
    x: 71.0
    y: 58.0
    z: -4.0
house:
  Bleu:
    color: §b
    spawn:
      x: 124.0
      y: 63.0
      z: -4.0
    coffre:
      x: 130.0
      y: 63.0
      z: -4.0
    porte:
      '0':
        x: 118.0
        y: 63.0
        z: -5.0
      '1':
        x: 118.0
        y: 63.0
        z: -4.0
      '2':
        x: 118.0
        y: 63.0
        z: -3.0
      '3':
        x: 118.0
        y: 64.0
        z: -3.0
      '4':
        x: 118.0
        y: 64.0
        z: -4.0
      '5':
        x: 118.0
        y: 64.0
        z: -5.0
      '6':
        x: 118.0
        y: 65.0
        z: -5.0
      '7':
        x: 118.0
        y: 65.0
        z: -4.0
      '8':
        x: 118.0
        y: 65.0
        z: -3.0
  Jaune:
    color: §e
    spawn:
      x: 83.0
      y: 63.0
      z: 38.0
    coffre:
      x: 83.0
      y: 63.0
      z: 44.0
    porte:
      '0':
        x: 84.0
        y: 65.0
        z: 32.0
      '1':
        x: 83.0
        y: 65.0
        z: 32.0
      '2':
        x: 82.0
        y: 65.0
        z: 32.0
      '3':
        x: 82.0
        y: 64.0
        z: 32.0
      '4':
        x: 83.0
        y: 64.0
        z: 32.0
      '5':
        x: 84.0
        y: 64.0
        z: 32.0
      '6':
        x: 84.0
        y: 63.0
        z: 32.0
      '7':
        x: 83.0
        y: 63.0
        z: 32.0
      '8':
        x: 82.0
        y: 63.0
        z: 32.0
  Rouge:
    color: §c
    spawn:
      x: 83.0
      y: 63.0
      z: -46.0
    coffre:
      x: 83.0
      y: 63.0
      z: -52.0
    porte:
      '0':
        x: 82.0
        y: 65.0
        z: -40.0
      '1':
        x: 83.0
        y: 65.0
        z: -40.0
      '2':
        x: 84.0
        y: 65.0
        z: -40.0
      '3':
        x: 84.0
        y: 64.0
        z: -40.0
      '4':
        x: 83.0
        y: 64.0
        z: -40.0
      '5':
        x: 82.0
        y: 64.0
        z: -40.0
      '6':
        x: 82.0
        y: 63.0
        z: -40.0
      '7':
        x: 83.0
        y: 63.0
        z: -40.0
      '8':
        x: 84.0
        y: 63.0
        z: -40.0

npcs:
  '0':
    x: 89.69892912279893
    y: 63.0
    z: -44.5069544809591
    pitch: 0.7498497
    yaw: 89.98773
  '1':
    x: 77.30000001192093
    y: 63.0
    z: 37.51996940973917
    pitch: 0.04937789
    yaw: 270.18524
  '2':
    x: 123.49256757104239
    y: 63.0
    z: 2.6996871193897096
    pitch: -0.5997644
    yaw: 179.98886


settings:
  protected_zone_area_radius: '55'
  mp_set_playzone_radius: '1000'
  arena_safezone_radius: '5'