map_name: house
default_spawn:
  x: -4
  y: 60
  z: -1918
arena:
  chest:
    x: -4.0
    y: 60.0
    z: -1918.0
  teleport:
    x: 6.0
    y: 63.0
    z: -1928.0
house:
  Jaune:
    color: §e
    spawn:
      x: -4.0
      y: 68.0
      z: -1956.0
    coffre:
      x: -4.0
      y: 68.0
      z: -1963.0
    porte:
      '0':
        x: -5.0
        y: 70.0
        z: -1949.0
      '1':
        x: -4.0
        y: 70.0
        z: -1949.0
      '2':
        x: -3.0
        y: 70.0
        z: -1949.0
      '3':
        x: -3.0
        y: 69.0
        z: -1949.0
      '4':
        x: -4.0
        y: 69.0
        z: -1949.0
      '5':
        x: -5.0
        y: 69.0
        z: -1949.0
      '6':
        x: -5.0
        y: 68.0
        z: -1949.0
      '7':
        x: -4.0
        y: 68.0
        z: -1949.0
      '8':
        x: -3.0
        y: 68.0
        z: -1949.0
  Bleu:
    color: §9
    spawn:
      x: 35.0
      y: 69.0
      z: -1918.0
    coffre:
      x: 41.0
      y: 69.0
      z: -1918.0
    porte:
      '0':
        x: 27.0
        y: 69.0
        z: -1917.0
      '1':
        x: 27.0
        y: 69.0
        z: -1918.0
      '2':
        x: 27.0
        y: 69.0
        z: -1919.0
      '3':
        x: 27.0
        y: 70.0
        z: -1919.0
      '4':
        x: 27.0
        y: 70.0
        z: -1918.0
      '5':
        x: 27.0
        y: 70.0
        z: -1917.0
      '6':
        x: 27.0
        y: 71.0
        z: -1917.0
      '7':
        x: 27.0
        y: 71.0
        z: -1918.0
      '8':
        x: 27.0
        y: 71.0
        z: -1919.0
  Rouge:
    color: §c
    spawn:
      x: -4.0
      y: 70.0
      z: -1879.0
    coffre:
      x: -4.0
      y: 70.0
      z: -1873.0
    porte:
      '0':
        x: -3.0
        y: 70.0
        z: -1887.0
      '1':
        x: -4.0
        y: 70.0
        z: -1887.0
      '2':
        x: -5.0
        y: 70.0
        z: -1887.0
      '3':
        x: -5.0
        y: 71.0
        z: -1887.0
      '4':
        x: -4.0
        y: 71.0
        z: -1887.0
      '5':
        x: -3.0
        y: 71.0
        z: -1887.0
      '6':
        x: -3.0
        y: 72.0
        z: -1887.0
      '7':
        x: -4.0
        y: 72.0
        z: -1887.0
      '8':
        x: -5.0
        y: 72.0
        z: -1887.0
  Vert:
    color: §a
    spawn:
      x: -43.0
      y: 69.0
      z: -1918.0
    coffre:
      x: -49.0
      y: 69.0
      z: -1918.0
    porte:
      '0':
        x: -35.0
        y: 69.0
        z: -1919.0
      '1':
        x: -35.0
        y: 69.0
        z: -1918.0
      '2':
        x: -35.0
        y: 69.0
        z: -1917.0
      '3':
        x: -35.0
        y: 70.0
        z: -1917.0
      '4':
        x: -35.0
        y: 70.0
        z: -1918.0
      '5':
        x: -35.0
        y: 70.0
        z: -1919.0
      '6':
        x: -35.0
        y: 71.0
        z: -1919.0
      '7':
        x: -35.0
        y: 71.0
        z: -1918.0
      '8':
        x: -35.0
        y: 71.0
        z: -1917.0
npcs:
  '0':
    x: -1.388419210645587
    y: 68.0
    z: -1950.4503979940775
    pitch: -3.4500384
    yaw: 91.25879
  '1':
    x: 29.535276517218932
    y: 69.0
    z: -1915.300000011921
    pitch: -4.6500335
    yaw: 180.36572
  '2':
    x: -5.69999998807907
    y: 70.0
    z: -1884.5574258506017
    pitch: -4.2000265
    yaw: 270.81152
  '3':
    x: -36.547974685234706
    y: 69.0
    z: -1919.661105872662
    pitch: 8.399976
    yaw: 1.0776367
settings:
  protected_zone_area_radius: 47
  mp_set_playzone_radius: 1000
