map_name: maison_moderne
default_spawn:
  x: -9
  y: 57
  z: -638
arena:
  chest:
    x: -9.0
    y: 57.0
    z: -638.0
  teleport:
    x: -19.0
    y: 60.0
    z: -648.0
house:
  Bleu:
    color: §9
    spawn:
      x: 29.0
      y: 65.0
      z: -638.0
    coffre:
      x: 36.0
      y: 65.0
      z: -638.0
    porte:
      '0':
        x: 22.0
        y: 67.0
        z: -637.0
      '1':
        x: 22.0
        y: 67.0
        z: -638.0
      '2':
        x: 22.0
        y: 67.0
        z: -639.0
      '3':
        x: 22.0
        y: 66.0
        z: -639.0
      '4':
        x: 22.0
        y: 66.0
        z: -638.0
      '5':
        x: 22.0
        y: 66.0
        z: -637.0
      '6':
        x: 22.0
        y: 65.0
        z: -637.0
      '7':
        x: 22.0
        y: 65.0
        z: -638.0
      '8':
        x: 22.0
        y: 65.0
        z: -639.0
  Jaune:
    color: §e
    spawn:
      x: -9.0
      y: 65.0
      z: -599.0
    coffre:
      x: -9.0
      y: 65.0
      z: -593.0
    porte:
      '0':
        x: -10.0
        y: 67.0
        z: -607.0
      '1':
        x: -9.0
        y: 67.0
        z: -607.0
      '2':
        x: -8.0
        y: 67.0
        z: -607.0
      '3':
        x: -8.0
        y: 66.0
        z: -607.0
      '4':
        x: -9.0
        y: 66.0
        z: -607.0
      '5':
        x: -10.0
        y: 66.0
        z: -607.0
      '6':
        x: -10.0
        y: 65.0
        z: -607.0
      '7':
        x: -9.0
        y: 65.0
        z: -607.0
      '8':
        x: -8.0
        y: 65.0
        z: -607.0
  Rouge:
    color: §c
    spawn:
      x: -48.0
      y: 65.0
      z: -638.0
    coffre:
      x: -55.0
      y: 65.0
      z: -638.0
    porte:
      '0':
        x: -41.0
        y: 67.0
        z: -639.0
      '1':
        x: -41.0
        y: 67.0
        z: -638.0
      '2':
        x: -41.0
        y: 67.0
        z: -637.0
      '3':
        x: -41.0
        y: 66.0
        z: -637.0
      '4':
        x: -41.0
        y: 66.0
        z: -638.0
      '5':
        x: -41.0
        y: 66.0
        z: -639.0
      '6':
        x: -41.0
        y: 65.0
        z: -639.0
      '7':
        x: -41.0
        y: 65.0
        z: -638.0
      '8':
        x: -41.0
        y: 65.0
        z: -637.0
  Vert:
    color: §a
    spawn:
      x: -9.0
      y: 65.0
      z: -676.0
    coffre:
      x: -9.0
      y: 65.0
      z: -683.0
    porte:
      '0':
        x: -8.0
        y: 67.0
        z: -669.0
      '1':
        x: -9.0
        y: 67.0
        z: -669.0
      '2':
        x: -10.0
        y: 67.0
        z: -669.0
      '3':
        x: -10.0
        y: 66.0
        z: -669.0
      '4':
        x: -9.0
        y: 66.0
        z: -669.0
      '5':
        x: -8.0
        y: 66.0
        z: -669.0
      '6':
        x: -8.0
        y: 65.0
        z: -669.0
      '7':
        x: -9.0
        y: 65.0
        z: -669.0
      '8':
        x: -10.0
        y: 65.0
        z: -669.0
npcs:
  '0':
    x: -1.811
    y: 65.0
    z: -598.995
    pitch: -1.1
    yaw: 90
  '1':
    x: -47
    y: 65.0
    z: -631.572
    pitch: 2.6
    yaw: 180.0
  '2':
    x: -14.77
    y: 65.0
    z: -676.11
    pitch: 1.8
    yaw: -89.6
  '3':
    x: 30.04
    y: 65.0
    z: -643.96
    pitch: -0.3
    yaw: 2.1

settings:
  protected_zone_area_radius: '54'
  arena_safezone_radius: '5'
  mp_set_playzone_radius: '1000'