map_name: mc_chinois_4t
default_spawn:
  x: 1231
  y: 60
  z: 1233
arena:
  chest:
    x: 1231.0
    y: 60.0
    z: 1233.0
  teleport:
    x: 1242.0
    y: 62.0
    z: 1222.0
house:
  Vert:
    color: §a
    spawn:
      x: 1231.0
      y: 68.0
      z: 1195.0
    coffre:
      x: 1231.0
      y: 68.0
      z: 1191.0
    porte:
      '0':
        x: 1230.0
        y: 70.0
        z: 1200.0
      '1':
        x: 1231.0
        y: 70.0
        z: 1200.0
      '2':
        x: 1232.0
        y: 70.0
        z: 1200.0
      '3':
        x: 1232.0
        y: 69.0
        z: 1200.0
      '4':
        x: 1231.0
        y: 69.0
        z: 1200.0
      '5':
        x: 1230.0
        y: 69.0
        z: 1200.0
      '6':
        x: 1230.0
        y: 68.0
        z: 1200.0
      '7':
        x: 1231.0
        y: 68.0
        z: 1200.0
      '8':
        x: 1232.0
        y: 68.0
        z: 1200.0
  Bleu:
    color: §b
    spawn:
      x: 1231.0
      y: 68.0
      z: 1271.0
    coffre:
      x: 1231.0
      y: 68.0
      z: 1275.0
    porte:
      '0':
        x: 1232.0
        y: 68.0
        z: 1266.0
      '1':
        x: 1231.0
        y: 68.0
        z: 1266.0
      '2':
        x: 1230.0
        y: 68.0
        z: 1266.0
      '3':
        x: 1230.0
        y: 69.0
        z: 1266.0
      '4':
        x: 1231.0
        y: 69.0
        z: 1266.0
      '5':
        x: 1232.0
        y: 69.0
        z: 1266.0
      '6':
        x: 1232.0
        y: 70.0
        z: 1266.0
      '7':
        x: 1231.0
        y: 70.0
        z: 1266.0
      '8':
        x: 1230.0
        y: 70.0
        z: 1266.0
  Rouge:
    color: §c
    spawn:
      x: 1269.0
      y: 68.0
      z: 1233.0
    coffre:
      x: 1273.0
      y: 68.0
      z: 1233.0
    porte:
      '0':
        x: 1264.0
        y: 68.0
        z: 1232.0
      '1':
        x: 1264.0
        y: 68.0
        z: 1233.0
      '2':
        x: 1264.0
        y: 68.0
        z: 1234.0
      '3':
        x: 1264.0
        y: 69.0
        z: 1234.0
      '4':
        x: 1264.0
        y: 69.0
        z: 1233.0
      '5':
        x: 1264.0
        y: 69.0
        z: 1232.0
      '6':
        x: 1264.0
        y: 70.0
        z: 1232.0
      '7':
        x: 1264.0
        y: 70.0
        z: 1233.0
      '8':
        x: 1264.0
        y: 70.0
        z: 1234.0
  Jaune:
    color: §e
    spawn:
      x: 1193.0
      y: 68.0
      z: 1233.0
    coffre:
      x: 1189.0
      y: 68.0
      z: 1233.0
    porte:
      '0':
        x: 1198.0
        y: 68.0
        z: 1232.0
      '1':
        x: 1198.0
        y: 68.0
        z: 1233.0
      '2':
        x: 1198.0
        y: 68.0
        z: 1234.0
      '3':
        x: 1198.0
        y: 69.0
        z: 1234.0
      '4':
        x: 1198.0
        y: 69.0
        z: 1233.0
      '5':
        x: 1198.0
        y: 69.0
        z: 1232.0
      '6':
        x: 1198.0
        y: 70.0
        z: 1232.0
      '7':
        x: 1198.0
        y: 70.0
        z: 1233.0
      '8':
        x: 1198.0
        y: 70.0
        z: 1234.0

npcs:
  '0':
    x: 1273.699999988079
    y: 68.0
    z: 1228.4522236001465
    pitch: 2.7000017
    yaw: 92.84741
  '1':
    x: 1226.4704037562637
    y: 68.0
    z: 1191.300000011921
    pitch: 0.7500205
    yaw: -0.45269838
  '2':
    x: 1189.300000011921
    y: 68.0
    z: 1238.4792135900511
    pitch: -1.8688028
    yaw: 269.445
  '3':
    x: 1236.5613129564376
    y: 68.0
    z: 1275.699999988079
    pitch: 2.5854492
    yaw: 178.22986


settings:
  protected_zone_area_radius: '60'
  arena_safezone_radius: '5'
  mp_set_playzone_radius: '1000'
