map_name: mc_chateaux
default_spawn:
  x: 226
  y: 61
  z: -87
arena:
  chest:
    x: 226.0
    y: 61.0
    z: -87.0
  teleport:
    x: 215.0
    y: 63.0
    z: -75.0
house:
  Bleu:
    color: §b
    spawn:
      x: 185.0
      y: 69.0
      z: -87.0
    coffre:
      x: 178.0
      y: 70.0
      z: -87.0
    porte:
      '0':
        x: 192.0
        y: 69.0
        z: -86.0
      '1':
        x: 192.0
        y: 69.0
        z: -87.0
      '2':
        x: 192.0
        y: 69.0
        z: -88.0
      '3':
        x: 192.0
        y: 70.0
        z: -88.0
      '4':
        x: 192.0
        y: 70.0
        z: -87.0
      '5':
        x: 192.0
        y: 70.0
        z: -86.0
      '6':
        x: 192.0
        y: 71.0
        z: -86.0
      '7':
        x: 192.0
        y: 71.0
        z: -87.0
      '8':
        x: 192.0
        y: 71.0
        z: -88.0
  Rouge:
    color: §c
    spawn:
      x: 267.0
      y: 69.0
      z: -87.0
    coffre:
      x: 274.0
      y: 70.0
      z: -87.0
    porte:
      '0':
        x: 260.0
        y: 69.0
        z: -88.0
      '1':
        x: 260.0
        y: 69.0
        z: -87.0
      '2':
        x: 260.0
        y: 69.0
        z: -86.0
      '3':
        x: 260.0
        y: 70.0
        z: -86.0
      '4':
        x: 260.0
        y: 70.0
        z: -87.0
      '5':
        x: 260.0
        y: 70.0
        z: -88.0
      '6':
        x: 260.0
        y: 71.0
        z: -88.0
      '7':
        x: 260.0
        y: 71.0
        z: -87.0
      '8':
        x: 260.0
        y: 71.0
        z: -86.0
  Vert:
    color: §a
    spawn:
      x: 226.0
      y: 69.0
      z: -46.0
    coffre:
      x: 226.0
      y: 70.0
      z: -39.0
    porte:
      '0':
        x: 227.0
        y: 69.0
        z: -53.0
      '1':
        x: 226.0
        y: 69.0
        z: -53.0
      '2':
        x: 225.0
        y: 69.0
        z: -53.0
      '3':
        x: 225.0
        y: 70.0
        z: -53.0
      '4':
        x: 226.0
        y: 70.0
        z: -53.0
      '5':
        x: 227.0
        y: 70.0
        z: -53.0
      '6':
        x: 227.0
        y: 71.0
        z: -53.0
      '7':
        x: 226.0
        y: 71.0
        z: -53.0
      '8':
        x: 225.0
        y: 71.0
        z: -53.0
  Jaune:
    color: §e
    spawn:
      x: 226.0
      y: 69.0
      z: -128.0
    coffre:
      x: 226.0
      y: 70.0
      z: -135.0
    porte:
      '0':
        x: 225.0
        y: 71.0
        z: -121.0
      '1':
        x: 226.0
        y: 71.0
        z: -121.0
      '2':
        x: 227.0
        y: 71.0
        z: -121.0
      '3':
        x: 227.0
        y: 70.0
        z: -121.0
      '4':
        x: 226.0
        y: 70.0
        z: -121.0
      '5':
        x: 225.0
        y: 70.0
        z: -121.0
      '6':
        x: 225.0
        y: 69.0
        z: -121.0
      '7':
        x: 226.0
        y: 69.0
        z: -121.0
      '8':
        x: 227.0
        y: 69.0
        z: -121.0

npcs:
  '0':
    x: 220.30643977169512
    y: 69.0
    z: -45.78656100989022
    pitch: 4.800002
    yaw: -89.99957
  '1':
    x: 186.0268976498155
    y: 69.0
    z: -92.69999998807907
    pitch: 3.300002
    yaw: 1.3523704
  '2':
    x: 267.1894473059259
    y: 69.0
    z: -80.30000001192093
    pitch: 2.6028821
    yaw: 179.82776
  '3':
    x: 232.69999998807907
    y: 69.0
    z: -127.18359196331029
    pitch: 3.6000025
    yaw: 89.55397


settings:
  protected_zone_area_radius: '55'
  mp_set_playzone_radius: '1000'
  arena_safezone_radius: '5'
