map_name: mc_4_elements
default_spawn:
  x: -231
  y: 62
  z: 116
arena:
  chest:
    x: -231.0
    y: 58.0
    z: 116.0
  teleport:
    x: -231.0
    y: 62.0
    z: 116.0
house:
  Mort:
    color: §e
    spawn:
      x: -231.0
      y: 68.0
      z: 76.0
    coffre:
      x: -231.0
      y: 68.0
      z: 70.0
    porte:
      '0':
        x: -230.0
        y: 70.0
        z: 83.0
      '1':
        x: -231.0
        y: 70.0
        z: 83.0
      '2':
        x: -232.0
        y: 70.0
        z: 83.0
      '3':
        x: -230.0
        y: 69.0
        z: 83.0
      '4':
        x: -231.0
        y: 69.0
        z: 83.0
      '5':
        x: -232.0
        y: 69.0
        z: 83.0
      '6':
        x: -230.0
        y: 68.0
        z: 83.0
      '7':
        x: -231.0
        y: 68.0
        z: 83.0
      '8':
        x: -232.0
        y: 68.0
        z: 83.0
  Eau:
    color: §b
    spawn:
      x: -271.0
      y: 68.0
      z: 116.0
    coffre:
      x: -277.0
      y: 68.0
      z: 116.0
    porte:
      '0':
        x: -263.0
        y: 70.0
        z: 115.0
      '1':
        x: -263.0
        y: 70.0
        z: 116.0
      '2':
        x: -263.0
        y: 70.0
        z: 117.0
      '3':
        x: -263.0
        y: 69.0
        z: 115.0
      '4':
        x: -263.0
        y: 69.0
        z: 116.0
      '5':
        x: -263.0
        y: 69.0
        z: 117.0
      '6':
        x: -263.0
        y: 68.0
        z: 115.0
      '7':
        x: -263.0
        y: 68.0
        z: 116.0
      '8':
        x: -263.0
        y: 68.0
        z: 117.0
  Nature:
    color: §a
    spawn:
      x: -231.0
      y: 68.0
      z: 154.0
    coffre:
      x: -227.0
      y: 68.0
      z: 153.0
    porte:
      '0':
        x: -232.0
        y: 70.0
        z: 149.0
      '1':
        x: -231.0
        y: 70.0
        z: 149.0
      '2':
        x: -230.0
        y: 70.0
        z: 149.0
      '3':
        x: -230.0
        y: 69.0
        z: 149.0
      '4':
        x: -231.0
        y: 69.0
        z: 149.0
      '5':
        x: -232.0
        y: 69.0
        z: 149.0
      '6':
        x: -232.0
        y: 68.0
        z: 149.0
      '7':
        x: -231.0
        y: 68.0
        z: 149.0
      '8':
        x: -230.0
        y: 68.0
        z: 149.0
  Feu:
    color: §c
    spawn:
      x: -191.0
      y: 68.0
      z: 120.0
    coffre:
      x: -186.0
      y: 68.0
      z: 116.0
    porte:
      '0':
        x: -197.0
        y: 70.0
        z: 117.0
      '1':
        x: -197.0
        y: 70.0
        z: 116.0
      '2':
        x: -197.0
        y: 70.0
        z: 115.0
      '3':
        x: -197.0
        y: 69.0
        z: 115.0
      '4':
        x: -197.0
        y: 69.0
        z: 116.0
      '5':
        x: -197.0
        y: 69.0
        z: 117.0
      '6':
        x: -197.0
        y: 68.0
        z: 117.0
      '7':
        x: -197.0
        y: 68.0
        z: 116.0
      '8':
        x: -197.0
        y: 68.0
        z: 115.0
npcs:
  '0':
    x: -194.5243907625249
    y: 68.0
    z: 118.72262358307172
    pitch: 0.44967428
    yaw: -179.84558
  '1':
    x: -233.69999998807907
    y: 68.0
    z: 152.4905642557667
    pitch: 1.1996801
    yaw: -89.52536
  '2':
    x: -271.4979096163059
    y: 68.0
    z: 113.05000001192093
    pitch: 0.29981637
    yaw: -359.071
  '3':
    x: -223.30000001192093
    y: 68.0
    z: 77.44156536873021
    pitch: 0.44981936
    yaw: -270.11407

settings:
  protected_zone_area_radius: 50
  mp_set_playzone_radius: 1000
