map_name: fars_west
default_spawn:
  x: 2826
  y: 65
  z: 1258
arena:
  chest:
    x: 2749.0
    y: 61.0
    z: 1251.0
  teleport:
    x: 2759.0
    y: 62.0
    z: 1241.0
house:
  Bleu:
    color: §9
    spawn:
      x: 2749.0
      y: 70.0
      z: 1290.0
    coffre:
      x: 2749.0
      y: 70.0
      z: 1294.0
    porte:
      '0':
        x: 2748.0
        y: 72.0
        z: 1285.0
      '1':
        x: 2749.0
        y: 72.0
        z: 1285.0
      '2':
        x: 2750.0
        y: 72.0
        z: 1285.0
      '3':
        x: 2750.0
        y: 71.0
        z: 1285.0
      '4':
        x: 2750.0
        y: 70.0
        z: 1285.0
      '5':
        x: 2749.0
        y: 70.0
        z: 1285.0
      '6':
        x: 2748.0
        y: 70.0
        z: 1285.0
      '7':
        x: 2748.0
        y: 71.0
        z: 1285.0
      '8':
        x: 2749.0
        y: 71.0
        z: 1285.0
  Jaune:
    color: §e
    spawn:
      x: 2711.0
      y: 70.0
      z: 1251.0
    coffre:
      x: 2706.0
      y: 70.0
      z: 1251.0
    porte:
      '0':
        x: 2715.0
        y: 72.0
        z: 1250.0
      '1':
        x: 2715.0
        y: 72.0
        z: 1251.0
      '2':
        x: 2715.0
        y: 72.0
        z: 1252.0
      '3':
        x: 2715.0
        y: 71.0
        z: 1252.0
      '4':
        x: 2715.0
        y: 70.0
        z: 1252.0
      '5':
        x: 2715.0
        y: 70.0
        z: 1251.0
      '6':
        x: 2715.0
        y: 70.0
        z: 1250.0
      '7':
        x: 2715.0
        y: 71.0
        z: 1250.0
      '8':
        x: 2715.0
        y: 71.0
        z: 1251.0
  Vert:
    color: §a
    spawn:
      x: 2749.0
      y: 70.0
      z: 1212.0
    coffre:
      x: 2749.0
      y: 70.0
      z: 1208.0
    porte:
      '0':
        x: 2750.0
        y: 72.0
        z: 1217.0
      '1':
        x: 2749.0
        y: 72.0
        z: 1217.0
      '2':
        x: 2748.0
        y: 72.0
        z: 1217.0
      '3':
        x: 2748.0
        y: 71.0
        z: 1217.0
      '4':
        x: 2748.0
        y: 70.0
        z: 1217.0
      '5':
        x: 2749.0
        y: 70.0
        z: 1217.0
      '6':
        x: 2750.0
        y: 70.0
        z: 1217.0
      '7':
        x: 2750.0
        y: 71.0
        z: 1217.0
      '8':
        x: 2749.0
        y: 71.0
        z: 1217.0
  Rouge:
    color: §c
    spawn:
      x: 2788.0
      y: 70.0
      z: 1251.0
    coffre:
      x: 2792.0
      y: 70.0
      z: 1251.0
    porte:
      '0':
        x: 2783.0
        y: 72.0
        z: 1252.0
      '1':
        x: 2783.0
        y: 72.0
        z: 1251.0
      '2':
        x: 2783.0
        y: 72.0
        z: 1250.0
      '3':
        x: 2783.0
        y: 71.0
        z: 1250.0
      '4':
        x: 2783.0
        y: 70.0
        z: 1250.0
      '5':
        x: 2783.0
        y: 70.0
        z: 1251.0
      '6':
        x: 2783.0
        y: 70.0
        z: 1252.0
      '7':
        x: 2783.0
        y: 71.0
        z: 1252.0
      '8':
        x: 2783.0
        y: 71.0
        z: 1251.0
npcs:
  '0':
    x: 2788.300000011921
    y: 70.0
    z: 1256.300000011921
    pitch: 2.268601
    yaw: 180.63092
  '1':
    x: 2744.699999988079
    y: 70.0
    z: 1290.300000011921
    pitch: 3.1350276
    yaw: -89.311195
  '2':
    x: 2754.300000011921
    y: 70.0
    z: 1212.699999988079
    pitch: 5.738669
    yaw: 90.470825
  '3':
    x: 2710.699999988079
    y: 70.0
    z: 1246.699999988079
    pitch: 1.4850559
    yaw: -0.65957963


settings:
  protected_zone_area_radius: '55'
  mp_set_playzone_radius: '1000'
  arena_safezone_radius: '5'