map_name: mc_4_players_map
arena:
  chest:
    x: -91.0
    y: 60.0
    z: 77.0
  teleport:
    x: -102.0
    y: 62.0
    z: 88.0
house:
  TeamJaune:
    color: §e
    spawn:
      x: -46.0
      y: 67.0
      z: 77.0
    coffre:
      x: -41.0
      y: 67.0
      z: 77.0
    porte:
      '0':
        x: -51.0
        y: 69.0
        z: 76.0
      '1':
        x: -51.0
        y: 69.0
        z: 77.0
      '2':
        x: -51.0
        y: 69.0
        z: 78.0
      '3':
        x: -51.0
        y: 68.0
        z: 78.0
      '4':
        x: -51.0
        y: 68.0
        z: 77.0
      '5':
        x: -51.0
        y: 68.0
        z: 76.0
      '6':
        x: -51.0
        y: 67.0
        z: 76.0
      '7':
        x: -51.0
        y: 67.0
        z: 77.0
      '8':
        x: -51.0
        y: 67.0
        z: 78.0
  TeamBleue:
    color: §1
    spawn:
      x: -91.0
      y: 67.0
      z: 120.0
    coffre:
      x: -91.0
      y: 67.0
      z: 125.0
    porte:
      '0':
        x: -92.0
        y: 69.0
        z: 115.0
      '1':
        x: -91.0
        y: 69.0
        z: 115.0
      '2':
        x: -90.0
        y: 69.0
        z: 115.0
      '3':
        x: -90.0
        y: 68.0
        z: 115.0
      '4':
        x: -91.0
        y: 68.0
        z: 115.0
      '5':
        x: -92.0
        y: 68.0
        z: 115.0
      '6':
        x: -92.0
        y: 67.0
        z: 115.0
      '7':
        x: -91.0
        y: 67.0
        z: 115.0
      '8':
        x: -90.0
        y: 67.0
        z: 115.0
  TeamVerte:
    color: §a
    spawn:
      x: -134.0
      y: 67.0
      z: 77.0
    coffre:
      x: -139.0
      y: 67.0
      z: 77.0
    porte:
      '0':
        x: -129.0
        y: 67.0
        z: 76.0
      '1':
        x: -129.0
        y: 67.0
        z: 77.0
      '2':
        x: -129.0
        y: 67.0
        z: 78.0
      '3':
        x: -129.0
        y: 68.0
        z: 78.0
      '4':
        x: -129.0
        y: 68.0
        z: 77.0
      '5':
        x: -129.0
        y: 68.0
        z: 76.0
      '6':
        x: -129.0
        y: 69.0
        z: 76.0
      '7':
        x: -129.0
        y: 69.0
        z: 77.0
      '8':
        x: -129.0
        y: 69.0
        z: 78.0
  TeamRouge:
    color: §c
    spawn:
      x: -91.0
      y: 67.0
      z: 33.0
    coffre:
      x: -91.0
      y: 67.0
      z: 28.0
    porte:
      '0':
        x: -90.0
        y: 69.0
        z: 38.0
      '1':
        x: -91.0
        y: 69.0
        z: 38.0
      '2':
        x: -92.0
        y: 69.0
        z: 38.0
      '3':
        x: -92.0
        y: 68.0
        z: 38.0
      '4':
        x: -91.0
        y: 68.0
        z: 38.0
      '5':
        x: -90.0
        y: 68.0
        z: 38.0
      '6':
        x: -90.0
        y: 67.0
        z: 38.0
      '7':
        x: -91.0
        y: 67.0
        z: 38.0
      '8':
        x: -92.0
        y: 67.0
        z: 38.0

npcs:
  '0':
    x: -41.66426605458243
    y: 67.0
    z: 81.81328522801263
    pitch: -0.14998722
    yaw: -224.39978
  '1':
    x: -85.99345564233644
    y: 67.0
    z: 28.906369162419963
    pitch: 0.45006245
    yaw: 42.450523
  '2':
    x: -137.0340997743755
    y: 67.0
    z: 73.0608961392197
    pitch: 2.4000616
    yaw: 317.3965
  '3':
    x: -94.74504378652813
    y: 67.0
    z: 125.02165323296556
    pitch: 1.5000615
    yaw: 210.89813

settings:
  mp_set_playzone_radius: '1000'
  protected_zone_area_radius: '55'

