map_name: egypte
default_spawn:
  x: 583
  y: 70
  z: 447
arena:
  chest:
    x: -73.0
    y: 77.0
    z: -70.0
  teleport:
    x: -72.0
    y: 82.0
    z: -69.0
house:
  Les_BG:
    color: §9
    spawn:
      x: -71.0
      y: 73.0
      z: -232.0
    coffre:
      x: -65.0
      y: 73.0
      z: -235.0
    porte:
      '0':
        x: -72.0
        y: 79.0
        z: -212.0
      '1':
        x: -73.0
        y: 79.0
        z: -212.0
      '2':
        x: -74.0
        y: 79.0
        z: -212.0
      '3':
        x: -74.0
        y: 80.0
        z: -212.0
      '4':
        x: -74.0
        y: 81.0
        z: -212.0
      '5':
        x: -73.0
        y: 81.0
        z: -212.0
      '6':
        x: -72.0
        y: 81.0
        z: -212.0
      '7':
        x: -72.0
        y: 80.0
        z: -212.0
      '8':
        x: -73.0
        y: 80.0
        z: -212.0
  Les_Marginalisés:
    color: §a
    spawn:
      x: -235.0
      y: 73.0
      z: -72.0
    coffre:
      x: -238.0
      y: 73.0
      z: -78.0
    porte:
      '0':
        x: -215.0
        y: 79.0
        z: -71.0
      '1':
        x: -215.0
        y: 79.0
        z: -70.0
      '2':
        x: -215.0
        y: 79.0
        z: -69.0
      '3':
        x: -215.0
        y: 80.0
        z: -69.0
      '4':
        x: -215.0
        y: 80.0
        z: -70.0
      '5':
        x: -215.0
        y: 80.0
        z: -71.0
      '6':
        x: -215.0
        y: 81.0
        z: -71.0
      '7':
        x: -215.0
        y: 81.0
        z: -70.0
      '8':
        x: -215.0
        y: 81.0
        z: -69.0
  Les_Erudits:
    color: §e
    spawn:
      x: -75.0
      y: 72.0
      z: 90.0
    coffre:
      x: -81.0
      y: 72.0
      z: 93.0
    porte:
      '0':
        x: -74.0
        y: 78.0
        z: 70.0
      '1':
        x: -73.0
        y: 78.0
        z: 70.0
      '2':
        x: -72.0
        y: 78.0
        z: 70.0
      '3':
        x: -72.0
        y: 79.0
        z: 70.0
      '4':
        x: -73.0
        y: 79.0
        z: 70.0
      '5':
        x: -74.0
        y: 79.0
        z: 70.0
      '6':
        x: -74.0
        y: 80.0
        z: 70.0
      '7':
        x: -73.0
        y: 80.0
        z: 70.0
      '8':
        x: -72.0
        y: 80.0
        z: 70.0
  Les_Dangereux:
    color: §c
    spawn:
      x: 89.0
      y: 72.0
      z: -68.0
    coffre:
      x: 92.0
      y: 72.0
      z: -62.0
    porte:
      '0':
        x: 69.0
        y: 80.0
        z: -69.0
      '1':
        x: 69.0
        y: 80.0
        z: -70.0
      '2':
        x: 69.0
        y: 80.0
        z: -71.0
      '3':
        x: 69.0
        y: 79.0
        z: -71.0
      '4':
        x: 69.0
        y: 79.0
        z: -70.0
      '5':
        x: 69.0
        y: 79.0
        z: -69.0
      '6':
        x: 69.0
        y: 78.0
        z: -69.0
      '7':
        x: 69.0
        y: 78.0
        z: -70.0
      '8':
        x: 69.0
        y: 78.0
        z: -71.0
npcs:
  '0':
    x: 83.30000001192093
    y: 72.0
    z: -73.69999998807907
    pitch: 0.86804974
    yaw: 314.14612
  '1':
    x: -68.30000001192093
    y: 72.0
    z: 84.30000001192093
    pitch: -0.3977053
    yaw: -306.9757
  '2':
    x: -76.69999998807907
    y: 73.0
    z: -225.30000001192093
    pitch: 1.268247
    yaw: 218.33282
  '3':
    x: -228.30000001192093
    y: 73.0
    z: -65.30000001192093
    pitch: 0.05228824
    yaw: -216.82628


settings:
  protected_zone_area_radius: '200'
  arena_safezone_radius: '5'
  mp_set_playzone_radius: '1000'
