map_name: nuke
default_spawn:
  x: 413
  y: 60
  z: -182
arena:
  chest:
    x: 413.0
    y: 60.0
    z: -182.0
  teleport:
    x: 405.0
    y: 63.0
    z: -174.0
house:
  Rouge:
    color: §c
    spawn:
      x: 379.0
      y: 68.0
      z: -180.0
    coffre:
      x: 381.0
      y: 68.0
      z: -182.0
    porte:
      '0':
        x: 385.0
        y: 70.0
        z: -181.0
      '1':
        x: 385.0
        y: 70.0
        z: -182.0
      '2':
        x: 385.0
        y: 70.0
        z: -183.0
      '3':
        x: 385.0
        y: 69.0
        z: -183.0
      '4':
        x: 385.0
        y: 69.0
        z: -182.0
      '5':
        x: 385.0
        y: 69.0
        z: -181.0
      '6':
        x: 385.0
        y: 68.0
        z: -181.0
      '7':
        x: 385.0
        y: 68.0
        z: -182.0
      '8':
        x: 385.0
        y: 68.0
        z: -183.0
  Jaune:
    color: §e
    spawn:
      x: 411.0
      y: 68.0
      z: -215.0
    coffre:
      x: 413.0
      y: 68.0
      z: -214.0
    porte:
      '0':
        x: 412.0
        y: 70.0
        z: -210.0
      '1':
        x: 413.0
        y: 70.0
        z: -210.0
      '2':
        x: 414.0
        y: 70.0
        z: -210.0
      '3':
        x: 414.0
        y: 69.0
        z: -210.0
      '4':
        x: 413.0
        y: 69.0
        z: -210.0
      '5':
        x: 412.0
        y: 69.0
        z: -210.0
      '6':
        x: 412.0
        y: 68.0
        z: -210.0
      '7':
        x: 413.0
        y: 68.0
        z: -210.0
      '8':
        x: 414.0
        y: 68.0
        z: -210.0
  Bleu:
    color: §9
    spawn:
      x: 447.0
      y: 70.0
      z: -184.0
    coffre:
      x: 446.0
      y: 70.0
      z: -182.0
    porte:
      '0':
        x: 442.0
        y: 72.0
        z: -183.0
      '1':
        x: 442.0
        y: 72.0
        z: -182.0
      '2':
        x: 442.0
        y: 72.0
        z: -181.0
      '3':
        x: 442.0
        y: 71.0
        z: -181.0
      '4':
        x: 442.0
        y: 71.0
        z: -182.0
      '5':
        x: 442.0
        y: 71.0
        z: -183.0
      '6':
        x: 442.0
        y: 70.0
        z: -183.0
      '7':
        x: 442.0
        y: 70.0
        z: -182.0
      '8':
        x: 442.0
        y: 70.0
        z: -181.0
  Vert:
    color: §a
    spawn:
      x: 415.0
      y: 67.0
      z: -149.0
    coffre:
      x: 413.0
      y: 67.0
      z: -150.0
    porte:
      '0':
        x: 414.0
        y: 69.0
        z: -154.0
      '1':
        x: 413.0
        y: 69.0
        z: -154.0
      '2':
        x: 412.0
        y: 69.0
        z: -154.0
      '3':
        x: 412.0
        y: 68.0
        z: -154.0
      '4':
        x: 413.0
        y: 68.0
        z: -154.0
      '5':
        x: 414.0
        y: 68.0
        z: -154.0
      '6':
        x: 414.0
        y: 67.0
        z: -154.0
      '7':
        x: 413.0
        y: 67.0
        z: -154.0
      '8':
        x: 412.0
        y: 67.0
        z: -154.0
npcs:
  '0':
    x: 383.5331315063488
    y: 68.0
    z: -185.31871737728787
    pitch: 3.2999983
    yaw: 1.6708984
  '1':
    x: 417.4616687697075
    y: 68.0
    z: -211.4986470238291
    pitch: 2.2500005
    yaw: 89.149414
  '2':
    x: 444.5203567263529
    y: 70.0
    z: -177.53201112910995
    pitch: 2.2500277
    yaw: 179.90625
  '3':
    x: 409.51654857009135
    y: 67.0
    z: -151.40039356188572
    pitch: 13.349997
    yaw: 270.5586

settings:
  protected_zone_area_radius: '41'
  arena_safezone_radius: '5'
  mp_set_playzone_radius: '1000'