config:
  cvar:
    mp_randomize_team: '0'
    mp_enable_item_drop: '1'
    SCORE_IRON: '10'
    SCORE_GOLD: '50'
    SCORE_DIAMOND: '150'
    SCORE_EMERALD: '300'
    mp_team_max_player: '3'
    mp_set_playzone_radius: '1000'
    mp_enable_friendly_fire: '1'
    mp_enable_old_pvp: '1'
    mp_enable_block_adding: '1'
    max_teleport_time: '15'
    max_item_in_chest: '20'
    min_item_in_chest: '10'
    death_time: '10'
  settings:
    game_time: '60'
    pre_game_timer: '10'
    protected_zone_area_radius: '50'
    enable_monster_in_protected_zone: '1'
    arena_safezone_radius: '4'
  arena:
    chest_opening_cooldown: '5'
    max_time_between_chests: '15'
    min_time_between_chests: '10'
    chicken_spawn_time: '10'
    chicken_spawn_interval: '30'
    chicken_spawn_min_count: '2'
    chicken_spawn_max_count: '5'
    chicken_spawn_min_item_count: '1'
    chicken_spawn_max_item_count: '3'
