map_name: nether
default_spawn: 'null'
arena:
  chest:
    x: 227.0
    y: 55.0
    z: -594.0
  teleport:
    x: 235.0
    y: 57.0
    z: -603.0
house:
  teamRouge:
    color: §c
    spawn:
      x: 227.0
      y: 64.0
      z: -555.0
    coffre:
      x: 227.0
      y: 64.0
      z: -551.0
    porte:
      '0':
        x: 228.0
        y: 66.0
        z: -561.0
      '1':
        x: 227.0
        y: 66.0
        z: -561.0
      '2':
        x: 226.0
        y: 66.0
        z: -561.0
      '3':
        x: 228.0
        y: 65.0
        z: -561.0
      '4':
        x: 227.0
        y: 65.0
        z: -561.0
      '5':
        x: 226.0
        y: 65.0
        z: -561.0
      '6':
        x: 228.0
        y: 64.0
        z: -561.0
      '7':
        x: 227.0
        y: 64.0
        z: -561.0
      '8':
        x: 226.0
        y: 64.0
        z: -561.0
  teamBleu:
    color: §9
    spawn:
      x: 188.0
      y: 64.0
      z: -594.0
    coffre:
      x: 184.0
      y: 64.0
      z: -594.0
    porte:
      '0':
        x: 194.0
        y: 66.0
        z: -593.0
      '1':
        x: 194.0
        y: 66.0
        z: -594.0
      '2':
        x: 194.0
        y: 66.0
        z: -595.0
      '3':
        x: 194.0
        y: 65.0
        z: -593.0
      '4':
        x: 194.0
        y: 65.0
        z: -594.0
      '5':
        x: 194.0
        y: 65.0
        z: -595.0
      '6':
        x: 194.0
        y: 64.0
        z: -593.0
      '7':
        x: 194.0
        y: 64.0
        z: -594.0
      '8':
        x: 194.0
        y: 64.0
        z: -595.0
  teamJaune:
    color: §e
    spawn:
      x: 227.0
      y: 64.0
      z: -633.0
    coffre:
      x: 227.0
      y: 64.0
      z: -637.0
    porte:
      '0':
        x: 226.0
        y: 66.0
        z: -627.0
      '1':
        x: 227.0
        y: 66.0
        z: -627.0
      '2':
        x: 228.0
        y: 66.0
        z: -627.0
      '3':
        x: 226.0
        y: 65.0
        z: -627.0
      '4':
        x: 227.0
        y: 65.0
        z: -627.0
      '5':
        x: 228.0
        y: 65.0
        z: -627.0
      '6':
        x: 226.0
        y: 64.0
        z: -627.0
      '7':
        x: 227.0
        y: 64.0
        z: -627.0
      '8':
        x: 228.0
        y: 64.0
        z: -627.0
  teamVerte:
    color: §a
    spawn:
      x: 266.0
      y: 64.0
      z: -594.0
    coffre:
      x: 270.0
      y: 64.0
      z: -594.0
    porte:
      '0':
        x: 260.0
        y: 66.0
        z: -595.0
      '1':
        x: 260.0
        y: 66.0
        z: -594.0
      '2':
        x: 260.0
        y: 66.0
        z: -593.0
      '3':
        x: 260.0
        y: 65.0
        z: -595.0
      '4':
        x: 260.0
        y: 65.0
        z: -594.0
      '5':
        x: 260.0
        y: 65.0
        z: -593.0
      '6':
        x: 260.0
        y: 64.0
        z: -595.0
      '7':
        x: 260.0
        y: 64.0
        z: -594.0
      '8':
        x: 260.0
        y: 64.0
        z: -593.0

npcs:
  '0':
    x: 266.5071787891707
    y: 64.0
    z: -588.3003072475541
    pitch: 1.4998555
    yaw: -180.24034
  '1':
    x: 188.48194488897082
    y: 64.0
    z: -598.6999999880791
    pitch: 1.0505966
    yaw: 359.81137
  '2':
    x: 232.69999998807907
    y: 64.0
    z: -632.5116680186551
    pitch: 0.15010817
    yaw: 90.2093
  '3':
    x: 222.30000001192093
    y: 64.0
    z: -554.4878032364396
    pitch: 2.4517498
    yaw: 269.7279


settings:
  mp_set_playzone_radius: '1000'
  protected_zone_area_radius: '50'
  arena_safezone_radius: '4'
