map_name: dmd
default_spawn:
  x: -200
  y: 59
  z: 166
arena:
  chest:
    x: -200.0
    y: 59.0
    z: 166.0
  teleport:
    x: -211.0
    y: 60.0
    z: 155.0
house:
  macdo:
    color: §c
    spawn:
      x: -236.0
      y: 67.0
      z: 166.0
    coffre:
      x: -239.0
      y: 67.0
      z: 166.0
    porte:
      '0':
        x: -232.0
        y: 69.0
        z: 167.0
      '1':
        x: -232.0
        y: 69.0
        z: 166.0
      '2':
        x: -232.0
        y: 69.0
        z: 165.0
      '3':
        x: -232.0
        y: 68.0
        z: 165.0
      '4':
        x: -232.0
        y: 68.0
        z: 166.0
      '5':
        x: -232.0
        y: 68.0
        z: 167.0
      '6':
        x: -232.0
        y: 67.0
        z: 167.0
      '7':
        x: -232.0
        y: 67.0
        z: 166.0
      '8':
        x: -232.0
        y: 67.0
        z: 165.0
  quick:
    color: §a
    spawn:
      x: -200.0
      y: 66.0
      z: 202.0
    coffre:
      x: -200.0
      y: 66.0
      z: 206.0
    porte:
      '0':
        x: -201.0
        y: 68.0
        z: 198.0
      '1':
        x: -200.0
        y: 68.0
        z: 198.0
      '2':
        x: -199.0
        y: 68.0
        z: 198.0
      '3':
        x: -199.0
        y: 67.0
        z: 198.0
      '4':
        x: -200.0
        y: 67.0
        z: 198.0
      '5':
        x: -201.0
        y: 67.0
        z: 198.0
      '6':
        x: -201.0
        y: 66.0
        z: 198.0
      '7':
        x: -200.0
        y: 66.0
        z: 198.0
      '8':
        x: -199.0
        y: 66.0
        z: 198.0
  burger-king:
    color: §9
    spawn:
      x: -162.0
      y: 66.0
      z: 166.0
    coffre:
      x: -157.0
      y: 66.0
      z: 164.0
    porte:
      '0':
        x: -167.0
        y: 68.0
        z: 167.0
      '1':
        x: -167.0
        y: 68.0
        z: 166.0
      '2':
        x: -167.0
        y: 68.0
        z: 165.0
      '3':
        x: -167.0
        y: 67.0
        z: 165.0
      '4':
        x: -167.0
        y: 67.0
        z: 166.0
      '5':
        x: -167.0
        y: 67.0
        z: 167.0
      '6':
        x: -167.0
        y: 66.0
        z: 167.0
      '7':
        x: -167.0
        y: 66.0
        z: 166.0
      '8':
        x: -167.0
        y: 66.0
        z: 165.0
  kfc:
    color: §e
    spawn:
      x: -200.0
      y: 64.0
      z: 129.0
    coffre:
      x: -200.0
      y: 64.0
      z: 125.0
    porte:
      '0':
        x: -199.0
        y: 66.0
        z: 133.0
      '1':
        x: -200.0
        y: 66.0
        z: 133.0
      '2':
        x: -201.0
        y: 66.0
        z: 133.0
      '3':
        x: -201.0
        y: 65.0
        z: 133.0
      '4':
        x: -200.0
        y: 65.0
        z: 133.0
      '5':
        x: -199.0
        y: 65.0
        z: 133.0
      '6':
        x: -199.0
        y: 64.0
        z: 133.0
      '7':
        x: -200.0
        y: 64.0
        z: 133.0
      '8':
        x: -201.0
        y: 64.0
        z: 133.0

npcs:
  '0':
    x: -235.2461293659388
    y: 67.0
    z: 168.69999998807907
    pitch: 2.935893
    yaw: 181.10626
  '1':
    x: -203.30000001192093
    y: 66.0
    z: 201.30000001192093
    pitch: 3.7498393
    yaw: -89.847626
  '2':
    x: -159.30000001192093
    y: 66.0
    z: 161.69999998807907
    pitch: 6.4058533
    yaw: 1.2844837
  '3':
    x: -196.69999998807907
    y: 64.0
    z: 130.69999998807907
    pitch: 0.2999413
    yaw: -270.29575


settings:
  mp_set_playzone_radius: '1000'
  protected_zone_area_radius: '55'
  arena_safezone_radius: '5'
