map_name: mc_bouseland
arena:
  chest:
    x: -142
    y: 58
    z: -92
  teleport:
    x: -156.5
    y: 57
    z: -76.5
house:
  Bleu ciel:
    color: §b
    spawn:
      x: -105
      y: 63
      z: -91
    coffre:
      x: -102
      y: 63
      z: -92
    porte:
      '0':
        x: -110
        y: 65
        z: -93
      '1':
        x: -110
        y: 65
        z: -92
      '2':
        x: -110
        y: 65
        z: -91
      '3':
        x: -110
        y: 64
        z: -93
      '4':
        x: -110
        y: 64
        z: -92
      '5':
        x: -110
        y: 64
        z: -91
      '6':
        x: -110
        y: 63
        z: -93
      '7':
        x: -110
        y: 63
        z: -92
      '8':
        x: -110
        y: 63
        z: -91
  Vert:
    color: §a
    spawn:
      x: -141
      y: 63
      z: -129
    coffre:
      x: -142
      y: 63
      z: -132
    porte:
      '0':
        x: -141
        y: 65
        z: -124
      '1':
        x: -142
        y: 65
        z: -124
      '2':
        x: -143
        y: 65
        z: -124
      '3':
        x: -141
        y: 64
        z: -124
      '4':
        x: -142
        y: 64
        z: -124
      '5':
        x: -143
        y: 64
        z: -124
      '6':
        x: -141
        y: 63
        z: -124
      '7':
        x: -142
        y: 63
        z: -124
      '8':
        x: -143
        y: 63
        z: -124
  Rouge:
    color: §c
    spawn:
      x: -178
      y: 63
      z: -92
    coffre:
      x: -182
      y: 63
      z: -92
    porte:
      '0':
        x: -174
        y: 65
        z: -93
      '1':
        x: -174
        y: 65
        z: -92
      '2':
        x: -174
        y: 65
        z: -91
      '3':
        x: -174
        y: 64
        z: -93
      '4':
        x: -174
        y: 64
        z: -92
      '5':
        x: -174
        y: 64
        z: -91
      '6':
        x: -174
        y: 63
        z: -93
      '7':
        x: -174
        y: 63
        z: -92
      '8':
        x: -174
        y: 63
        z: -91
  Jaune:
    color: §e
    spawn:
      x: -144
      y: 63
      z: -55
    coffre:
      x: -142
      y: 63
      z: -52
    porte:
      '0':
        x: -143
        y: 65
        z: -60
      '1':
        x: -142
        y: 65
        z: -60
      '2':
        x: -141
        y: 65
        z: -60
      '3':
        x: -143
        y: 64
        z: -60
      '4':
        x: -142
        y: 64
        z: -60
      '5':
        x: -141
        y: 64
        z: -60
      '6':
        x: -143
        y: 63
        z: -60
      '7':
        x: -142
        y: 63
        z: -60
      '8':
        x: -141
        y: 63
        z: -60
npcs:
  '0':
    x: -108.34948221781185
    y: 63.0
    z: -85.30000001192093
    yaw: 179.85345
    pitch: 1.9502522
  '1':
    x: -135.30000001192093
    y: 63.0
    z: -125.69516558815417
    yaw: 90.15158
    pitch: 0.300174
  '2':
    x: -175.51447163261878
    y: 63.0
    z: -97.69999998807904
    yaw: 1.1997375
    pitch: 1.2001611
  '3':
    x: -147.69999998807907
    y: 63.0
    z: -56.30000001192093
    yaw: 272.54514
    pitch: 3.900158
settings:
  protected_zone_area_radius: 42
  mp_set_playzone_radius: 1000
