map_name: Subnautica
arena:
  chest:
    x: -136
    y: 200
    z: -99
  teleport:
    x: -136
    y: 220
    z: -99
house:
  Bleu:
    color: §9
    spawn:
      x: -136
      y: 79
      z: -185
    coffre:
      x: -136
      y: 79
      z: -194
    porte:
      '0':
        x: -133
        y: 83
        z: -174
      '1':
        x: -133
        y: 82
        z: -174
      '2':
        x: -133
        y: 81
        z: -174
      '3':
        x: -133
        y: 80
        z: -174
      '4':
        x: -134
        y: 80
        z: -174
      '5':
        x: -134
        y: 81
        z: -174
      '6':
        x: -134
        y: 82
        z: -174
      '7':
        x: -134
        y: 83
        z: -174
      '8':
        x: -135
        y: 83
        z: -174
      '9':
        x: -135
        y: 82
        z: -174
      '10':
        x: -135
        y: 81
        z: -174
      '11':
        x: -135
        y: 80
        z: -174
      '12':
        x: -136
        y: 80
        z: -174
      '13':
        x: -136
        y: 81
        z: -174
      '14':
        x: -136
        y: 82
        z: -174
      '15':
        x: -136
        y: 83
        z: -174
      '16':
        x: -137
        y: 83
        z: -174
      '17':
        x: -137
        y: 82
        z: -174
      '18':
        x: -137
        y: 81
        z: -174
      '19':
        x: -137
        y: 80
        z: -174
      '20':
        x: -138
        y: 80
        z: -174
      '21':
        x: -138
        y: 81
        z: -174
      '22':
        x: -138
        y: 82
        z: -174
      '23':
        x: -138
        y: 83
        z: -174
      '24':
        x: -139
        y: 83
        z: -174
      '25':
        x: -139
        y: 82
        z: -174
      '26':
        x: -139
        y: 81
        z: -174
      '27':
        x: -139
        y: 80
        z: -174
  Rouge:
    color: §c
    spawn:
      x: -136
      y: 79
      z: -12
    coffre:
      x: -136
      y: 79
      z: -3
    porte:
      '0':
        x: -139
        y: 83
        z: -23
      '1':
        x: -139
        y: 82
        z: -23
      '2':
        x: -139
        y: 81
        z: -23
      '3':
        x: -139
        y: 80
        z: -23
      '4':
        x: -138
        y: 80
        z: -23
      '5':
        x: -138
        y: 81
        z: -23
      '6':
        x: -138
        y: 82
        z: -23
      '7':
        x: -138
        y: 83
        z: -23
      '8':
        x: -137
        y: 83
        z: -23
      '9':
        x: -137
        y: 82
        z: -23
      '10':
        x: -137
        y: 81
        z: -23
      '11':
        x: -137
        y: 80
        z: -23
      '12':
        x: -136
        y: 80
        z: -23
      '13':
        x: -136
        y: 81
        z: -23
      '14':
        x: -136
        y: 82
        z: -23
      '15':
        x: -136
        y: 83
        z: -23
      '16':
        x: -135
        y: 83
        z: -23
      '17':
        x: -135
        y: 82
        z: -23
      '18':
        x: -135
        y: 81
        z: -23
      '19':
        x: -135
        y: 80
        z: -23
      '20':
        x: -134
        y: 80
        z: -23
      '21':
        x: -134
        y: 81
        z: -23
      '22':
        x: -134
        y: 82
        z: -23
      '23':
        x: -134
        y: 83
        z: -23
      '24':
        x: -133
        y: 83
        z: -23
      '25':
        x: -133
        y: 82
        z: -23
      '26':
        x: -133
        y: 81
        z: -23
      '27':
        x: -133
        y: 80
        z: -23
  Jaune:
    color: §e
    spawn:
      x: -222
      y: 79
      z: -99
    coffre:
      x: -231
      y: 79
      z: -99
    porte:
      '0':
        x: -211
        y: 83
        z: -102
      '1':
        x: -211
        y: 82
        z: -102
      '2':
        x: -211
        y: 81
        z: -102
      '3':
        x: -211
        y: 80
        z: -102
      '4':
        x: -211
        y: 80
        z: -101
      '5':
        x: -211
        y: 81
        z: -101
      '6':
        x: -211
        y: 82
        z: -101
      '7':
        x: -211
        y: 83
        z: -101
      '8':
        x: -211
        y: 83
        z: -100
      '9':
        x: -211
        y: 82
        z: -100
      '10':
        x: -211
        y: 81
        z: -100
      '11':
        x: -211
        y: 80
        z: -100
      '12':
        x: -211
        y: 80
        z: -99
      '13':
        x: -211
        y: 81
        z: -99
      '14':
        x: -211
        y: 82
        z: -99
      '15':
        x: -211
        y: 83
        z: -99
      '16':
        x: -211
        y: 83
        z: -98
      '17':
        x: -211
        y: 82
        z: -98
      '18':
        x: -211
        y: 81
        z: -98
      '19':
        x: -211
        y: 80
        z: -98
      '20':
        x: -211
        y: 80
        z: -97
      '21':
        x: -211
        y: 81
        z: -97
      '22':
        x: -211
        y: 82
        z: -97
      '23':
        x: -211
        y: 83
        z: -97
      '24':
        x: -211
        y: 83
        z: -96
      '25':
        x: -211
        y: 82
        z: -96
      '26':
        x: -211
        y: 81
        z: -96
      '27':
        x: -211
        y: 80
        z: -96
  Vert:
    color: §a
    spawn:
      x: -50
      y: 79
      z: -99
    coffre:
      x: -41
      y: 79
      z: -99
    porte:
      '0':
        x: -61
        y: 83
        z: -96
      '1':
        x: -61
        y: 82
        z: -96
      '2':
        x: -61
        y: 81
        z: -96
      '3':
        x: -61
        y: 80
        z: -96
      '4':
        x: -61
        y: 80
        z: -97
      '5':
        x: -61
        y: 81
        z: -97
      '6':
        x: -61
        y: 82
        z: -97
      '7':
        x: -61
        y: 83
        z: -97
      '8':
        x: -61
        y: 83
        z: -98
      '9':
        x: -61
        y: 82
        z: -98
      '10':
        x: -61
        y: 81
        z: -98
      '11':
        x: -61
        y: 80
        z: -98
      '12':
        x: -61
        y: 80
        z: -99
      '13':
        x: -61
        y: 81
        z: -99
      '14':
        x: -61
        y: 82
        z: -99
      '15':
        x: -61
        y: 83
        z: -99
      '16':
        x: -61
        y: 83
        z: -100
      '17':
        x: -61
        y: 82
        z: -100
      '18':
        x: -61
        y: 81
        z: -100
      '19':
        x: -61
        y: 80
        z: -100
      '20':
        x: -61
        y: 80
        z: -101
      '21':
        x: -61
        y: 81
        z: -101
      '22':
        x: -61
        y: 82
        z: -101
      '23':
        x: -61
        y: 83
        z: -101
      '24':
        x: -61
        y: 83
        z: -102
      '25':
        x: -61
        y: 82
        z: -102
      '26':
        x: -61
        y: 81
        z: -102
      '27':
        x: -61
        y: 80
        z: -102
npcs:
  '0':
    x: -169.9711258962248
    y: 78.0
    z: -184.43947872785378
    yaw: -89.68457
    pitch: -7.650066
  '1':
    x: -100.56448759420425
    y: 78.0
    z: -11.62697774890977
    yaw: -270.2223
    pitch: -2.7000172
  '2':
    x: -221.58368285536838
    y: 78.0
    z: -63.68796695040445
    yaw: -179.87402
    pitch: -2.0999594
  '3':
    x: -49.56242877615709
    y: 78.0
    z: -134.4179145503899
    yaw: -0.04348755
    pitch: -2.5505054
settings:
  protected_zone_area_radius: 56
  mp_set_playzone_radius: 1000
