map_name: Lune
default_spawn:
  x: 51
  y: 42
  z: -312
arena:
  chest:
    x: 55.0
    y: 67.0
    z: -312.0
  teleport:
    x: 55.0
    y: 83.0
    z: -312.0
house:
  Delta:
    color: §e
    spawn:
      x: -39.0
      y: 65.0
      z: -311.0
    coffre:
      x: -48.0
      y: 65.0
      z: -311.0
    porte:
      '0':
        x: -11.0
        y: 67.0
        z: -314.0
      '1':
        x: -11.0
        y: 67.0
        z: -313.0
      '2':
        x: -11.0
        y: 67.0
        z: -312.0
      '3':
        x: -11.0
        y: 67.0
        z: -311.0
      '4':
        x: -11.0
        y: 67.0
        z: -310.0
      '5':
        x: -11.0
        y: 67.0
        z: -309.0
      '6':
        x: -11.0
        y: 66.0
        z: -314.0
      '7':
        x: -11.0
        y: 66.0
        z: -313.0
      '8':
        x: -11.0
        y: 66.0
        z: -312.0
      '9':
        x: -11.0
        y: 66.0
        z: -311.0
      '10':
        x: -11.0
        y: 66.0
        z: -310.0
      '11':
        x: -11.0
        y: 66.0
        z: -309.0
      '12':
        x: -11.0
        y: 65.0
        z: -309.0
      '13':
        x: -11.0
        y: 65.0
        z: -310.0
      '14':
        x: -11.0
        y: 65.0
        z: -311.0
      '15':
        x: -11.0
        y: 65.0
        z: -312.0
      '16':
        x: -11.0
        y: 65.0
        z: -313.0
      '17':
        x: -11.0
        y: 65.0
        z: -314.0
  Alpha:
    color: §c
    spawn:
      x: 54.0
      y: 65.0
      z: -408.0
    coffre:
      x: 54.0
      y: 65.0
      z: -415.0
    porte:
      '0':
        x: 57.0
        y: 67.0
        z: -378.0
      '1':
        x: 56.0
        y: 67.0
        z: -378.0
      '2':
        x: 55.0
        y: 67.0
        z: -378.0
      '3':
        x: 54.0
        y: 67.0
        z: -378.0
      '4':
        x: 53.0
        y: 67.0
        z: -378.0
      '5':
        x: 52.0
        y: 67.0
        z: -378.0
      '6':
        x: 52.0
        y: 66.0
        z: -378.0
      '7':
        x: 53.0
        y: 66.0
        z: -378.0
      '8':
        x: 54.0
        y: 66.0
        z: -378.0
      '9':
        x: 55.0
        y: 66.0
        z: -378.0
      '10':
        x: 56.0
        y: 66.0
        z: -378.0
      '11':
        x: 57.0
        y: 66.0
        z: -378.0
      '12':
        x: 57.0
        y: 65.0
        z: -378.0
      '13':
        x: 56.0
        y: 65.0
        z: -378.0
      '14':
        x: 55.0
        y: 65.0
        z: -378.0
      '15':
        x: 54.0
        y: 65.0
        z: -378.0
      '16':
        x: 53.0
        y: 65.0
        z: -378.0
      '17':
        x: 52.0
        y: 65.0
        z: -378.0
  Bravo:
    color: §9
    spawn:
      x: 146.0
      y: 65.0
      z: -312.0
    coffre:
      x: 158.0
      y: 65.0
      z: -313.0
    porte:
      '0':
        x: 121.0
        y: 67.0
        z: -310.0
      '1':
        x: 121.0
        y: 67.0
        z: -311.0
      '2':
        x: 121.0
        y: 67.0
        z: -312.0
      '3':
        x: 121.0
        y: 67.0
        z: -313.0
      '4':
        x: 121.0
        y: 67.0
        z: -314.0
      '5':
        x: 121.0
        y: 67.0
        z: -315.0
      '6':
        x: 121.0
        y: 66.0
        z: -315.0
      '7':
        x: 121.0
        y: 66.0
        z: -314.0
      '8':
        x: 121.0
        y: 66.0
        z: -313.0
      '9':
        x: 121.0
        y: 66.0
        z: -312.0
      '10':
        x: 121.0
        y: 66.0
        z: -311.0
      '11':
        x: 121.0
        y: 66.0
        z: -310.0
      '12':
        x: 121.0
        y: 65.0
        z: -310.0
      '13':
        x: 121.0
        y: 65.0
        z: -311.0
      '14':
        x: 121.0
        y: 65.0
        z: -312.0
      '15':
        x: 121.0
        y: 65.0
        z: -313.0
      '16':
        x: 121.0
        y: 65.0
        z: -314.0
      '17':
        x: 121.0
        y: 65.0
        z: -315.0
  Charly:
    color: §a
    spawn:
      x: 55.0
      y: 65.0
      z: -221.0
    coffre:
      x: 56.0
      y: 65.0
      z: -209.0
    porte:
      '0':
        x: 53.0
        y: 67.0
        z: -246.0
      '1':
        x: 54.0
        y: 67.0
        z: -246.0
      '2':
        x: 55.0
        y: 67.0
        z: -246.0
      '3':
        x: 56.0
        y: 67.0
        z: -246.0
      '4':
        x: 57.0
        y: 67.0
        z: -246.0
      '5':
        x: 58.0
        y: 67.0
        z: -246.0
      '6':
        x: 58.0
        y: 66.0
        z: -246.0
      '7':
        x: 57.0
        y: 66.0
        z: -246.0
      '8':
        x: 56.0
        y: 66.0
        z: -246.0
      '9':
        x: 55.0
        y: 66.0
        z: -246.0
      '10':
        x: 54.0
        y: 66.0
        z: -246.0
      '11':
        x: 53.0
        y: 66.0
        z: -246.0
      '12':
        x: 53.0
        y: 65.0
        z: -246.0
      '13':
        x: 54.0
        y: 65.0
        z: -246.0
      '14':
        x: 55.0
        y: 65.0
        z: -246.0
      '15':
        x: 56.0
        y: 65.0
        z: -246.0
      '16':
        x: 57.0
        y: 65.0
        z: -246.0
      '17':
        x: 58.0
        y: 65.0
        z: -246.0
npcs:
    '0':
        x: 17.614661632386614
        y: 65.0
        z: -400.45037555123025
        pitch: -1.2004058
        yaw: -90.297455
    '1':
        x: -33.35128543640808
        y: 65.0
        z: -273.7341852313234
        pitch: 0.44958273
        yaw: -180.14658
    '2':
        x: 93.53049124710934
        y: 65.0
        z: -222.59182438173238
        pitch: -0.4503582
        yaw: -269.84683
    '3':
        x: 144.42103853189332
        y: 65.0
        z: -349.22400367707667
        pitch: 0.8996255
        yaw: -0.14602661


settings:
  protected_zone_area_radius: '79'
  arena_safezone_radius: '10'
  mp_set_playzone_radius: '1036'
