map_name: modern
default_spawn: 'null'
arena:
  chest:
    x: 6013.0
    y: 57.0
    z: 12008.0
  teleport:
    x: 6028.0
    y: 58.0
    z: 11994.0
house:
  TeamRouge:
    color: §c
    spawn:
      x: 6013.0
      y: 64.0
      z: 12067.0
    coffre:
      x: 6013.0
      y: 64.0
      z: 12070.0
    porte:
      '0':
        x: 6012.0
        y: 66.0
        z: 12061.0
      '1':
        x: 6013.0
        y: 66.0
        z: 12061.0
      '2':
        x: 6014.0
        y: 66.0
        z: 12061.0
      '3':
        x: 6012.0
        y: 65.0
        z: 12061.0
      '4':
        x: 6013.0
        y: 65.0
        z: 12061.0
      '5':
        x: 6014.0
        y: 65.0
        z: 12061.0
      '6':
        x: 6012.0
        y: 64.0
        z: 12061.0
      '7':
        x: 6013.0
        y: 64.0
        z: 12061.0
      '8':
        x: 6014.0
        y: 64.0
        z: 12061.0
  TeamVerte:
    color: §a
    spawn:
      x: 5953.0
      y: 64.0
      z: 12008.0
    coffre:
      x: 5950.0
      y: 64.0
      z: 12008.0
    porte:
      '0':
        x: 5959.0
        y: 66.0
        z: 12009.0
      '1':
        x: 5959.0
        y: 66.0
        z: 12008.0
      '2':
        x: 5959.0
        y: 66.0
        z: 12007.0
      '3':
        x: 5959.0
        y: 65.0
        z: 12009.0
      '4':
        x: 5959.0
        y: 65.0
        z: 12008.0
      '5':
        x: 5959.0
        y: 65.0
        z: 12007.0
      '6':
        x: 5959.0
        y: 64.0
        z: 12009.0
      '7':
        x: 5959.0
        y: 64.0
        z: 12008.0
      '8':
        x: 5959.0
        y: 64.0
        z: 12007.0
  TeamBleu:
    color: §9
    spawn:
      x: 6013.0
      y: 64.0
      z: 11950.0
    coffre:
      x: 6013.0
      y: 64.0
      z: 11946.0
    porte:
      '0':
        x: 6012.0
        y: 66.0
        z: 11955.0
      '1':
        x: 6013.0
        y: 66.0
        z: 11955.0
      '2':
        x: 6014.0
        y: 66.0
        z: 11955.0
      '3':
        x: 6012.0
        y: 65.0
        z: 11955.0
      '4':
        x: 6013.0
        y: 65.0
        z: 11955.0
      '5':
        x: 6014.0
        y: 65.0
        z: 11955.0
      '6':
        x: 6012.0
        y: 64.0
        z: 11955.0
      '7':
        x: 6013.0
        y: 64.0
        z: 11955.0
      '8':
        x: 6014.0
        y: 64.0
        z: 11955.0
  TeamJaune:
    color: §e
    spawn:
      x: 6072.0
      y: 64.0
      z: 12008.0
    coffre:
      x: 6076.0
      y: 64.0
      z: 12008.0
    porte:
      '0':
        x: 6067.0
        y: 66.0
        z: 12007.0
      '1':
        x: 6067.0
        y: 66.0
        z: 12008.0
      '2':
        x: 6067.0
        y: 66.0
        z: 12009.0
      '3':
        x: 6067.0
        y: 65.0
        z: 12007.0
      '4':
        x: 6067.0
        y: 65.0
        z: 12008.0
      '5':
        x: 6067.0
        y: 65.0
        z: 12009.0
      '6':
        x: 6067.0
        y: 64.0
        z: 12007.0
      '7':
        x: 6067.0
        y: 64.0
        z: 12008.0
      '8':
        x: 6067.0
        y: 64.0
        z: 12009.0

npcs:
  '0':
    x: 6018.699999988079
    y: 64.0
    z: 11950.454382617441
    pitch: 3.052313
    yaw: 90.15216

  '1':
    x: 6072.489761610266
    y: 64.0
    z: 12013.699999988079
    pitch: -1.675263E-4
    yaw: 179.73303

  '2':
    x: 6008.300000011921
    y: 64.0
    z: 12066.534665128416
    pitch: 0.9837016
    yaw: 269.50522

  '3':
    x: 5954.531783376979
    y: 64.0
    z: 12003.300000011921
    pitch: 0.38320464
    yaw: 0.3862915




settings:
  protected_zone_area_radius: '70'
  mp_set_playzone_radius: '1000'
  arena_safezone_radius: '4'