map_name: Nether
arena:
  chest:
    x: 1079
    y: 129
    z: -548
  teleport:
    x: 1079
    y: 113
    z: -548
house:
  Vert:
    color: §a
    spawn:
      x: 1079
      y: 114
      z: -624
    coffre:
      x: 1079
      y: 115
      z: -631
    porte:
      '0':
        x: 1080
        y: 115
        z: -609
      '1':
        x: 1080
        y: 115
        z: -608
      '2':
        x: 1079
        y: 115
        z: -608
      '3':
        x: 1078
        y: 115
        z: -608
      '4':
        x: 1077
        y: 115
        z: -608
      '5':
        x: 1077
        y: 115
        z: -609
      '6':
        x: 1077
        y: 114
        z: -608
      '7':
        x: 1078
        y: 114
        z: -607
      '8':
        x: 1077
        y: 114
        z: -607
      '9':
        x: 1079
        y: 114
        z: -607
      '10':
        x: 1080
        y: 114
        z: -607
      '11':
        x: 1080
        y: 114
        z: -608
      '12':
        x: 1080
        y: 116
        z: -608
      '13':
        x: 1079
        y: 116
        z: -608
      '14':
        x: 1078
        y: 116
        z: -608
      '15':
        x: 1077
        y: 116
        z: -608
  Rouge:
    color: §c
    spawn:
      x: 1155
      y: 114
      z: -548
    coffre:
      x: 1162
      y: 115
      z: -548
    porte:
      '0':
        x: 1140
        y: 115
        z: -547
      '1':
        x: 1139
        y: 115
        z: -547
      '2':
        x: 1139
        y: 115
        z: -548
      '3':
        x: 1139
        y: 115
        z: -549
      '4':
        x: 1139
        y: 115
        z: -550
      '5':
        x: 1140
        y: 115
        z: -550
      '6':
        x: 1139
        y: 114
        z: -550
      '7':
        x: 1138
        y: 114
        z: -550
      '8':
        x: 1138
        y: 114
        z: -549
      '9':
        x: 1138
        y: 114
        z: -548
      '10':
        x: 1138
        y: 114
        z: -547
      '11':
        x: 1139
        y: 114
        z: -547
      '12':
        x: 1139
        y: 116
        z: -547
      '13':
        x: 1139
        y: 116
        z: -548
      '14':
        x: 1139
        y: 116
        z: -549
      '15':
        x: 1139
        y: 116
        z: -550
  Bleu:
    color: §9
    spawn:
      x: 1079
      y: 114
      z: -472
    coffre:
      x: 1079
      y: 115
      z: -465
    porte:
      '0':
        x: 1078
        y: 115
        z: -487
      '1':
        x: 1078
        y: 115
        z: -488
      '2':
        x: 1079
        y: 115
        z: -488
      '3':
        x: 1080
        y: 115
        z: -488
      '4':
        x: 1081
        y: 115
        z: -488
      '5':
        x: 1081
        y: 115
        z: -487
      '6':
        x: 1081
        y: 116
        z: -488
      '7':
        x: 1080
        y: 116
        z: -488
      '8':
        x: 1079
        y: 116
        z: -488
      '9':
        x: 1078
        y: 116
        z: -488
      '10':
        x: 1078
        y: 114
        z: -488
      '11':
        x: 1078
        y: 114
        z: -489
      '12':
        x: 1079
        y: 114
        z: -489
      '13':
        x: 1080
        y: 114
        z: -489
      '14':
        x: 1081
        y: 114
        z: -489
      '15':
        x: 1081
        y: 114
        z: -488
  Jaune:
    color: §e
    spawn:
      x: 1003
      y: 114
      z: -548
    coffre:
      x: 996
      y: 115
      z: -548
    porte:
      '0':
        x: 1018
        y: 115
        z: -549
      '1':
        x: 1019
        y: 115
        z: -549
      '2':
        x: 1019
        y: 115
        z: -548
      '3':
        x: 1019
        y: 115
        z: -547
      '4':
        x: 1019
        y: 115
        z: -546
      '5':
        x: 1018
        y: 115
        z: -546
      '6':
        x: 1019
        y: 114
        z: -546
      '7':
        x: 1020
        y: 114
        z: -546
      '8':
        x: 1020
        y: 114
        z: -547
      '9':
        x: 1020
        y: 114
        z: -548
      '10':
        x: 1020
        y: 114
        z: -549
      '11':
        x: 1019
        y: 114
        z: -549
      '12':
        x: 1019
        y: 116
        z: -549
      '13':
        x: 1019
        y: 116
        z: -548
      '14':
        x: 1019
        y: 116
        z: -547
      '15':
        x: 1019
        y: 116
        z: -546
npcs:
  '0':
    x: 1083.5652875108217
    y: 114.0
    z: -616.6999999880791
    yaw: -0.6055603
    pitch: 5.400798
  '1':
    x: 1148.699999988079
    y: 114.0
    z: -543.4042095135379
    yaw: -269.40656
    pitch: -0.7502953
  '2':
    x: 1075.5333012291337
    y: 114.0
    z: -478.30000001192093
    yaw: -180.31543
    pitch: -1.6503526
  '3':
    x: 1010.3000000119209
    y: 114.0
    z: -551.423484025392
    yaw: -90.74402
    pitch: 0.8997354
settings:
  protected_zone_area_radius: 89
  mp_set_playzone_radius: 1000
