map_name: arbre4team
default_spawn: 
  x: 87.0
  y: 56.0
  z: -81.0
arena:
  chest:
    x: 87.0
    y: 56.0
    z: -81.0
  teleport:
    x: 98.0
    y: 59.0
    z: -92.0
house:
  rouge:
    color: §c
    spawn:
      x: 86.0
      y: 64.0
      z: -41.0
    coffre:
      x: 83.0
      y: 64.0
      z: -36.0
    porte:
      '0':
        x: 86.0
        y: 66.0
        z: -46.0
      '1':
        x: 87.0
        y: 66.0
        z: -46.0
      '2':
        x: 88.0
        y: 66.0
        z: -46.0
      '3':
        x: 88.0
        y: 65.0
        z: -46.0
      '4':
        x: 87.0
        y: 65.0
        z: -46.0
      '5':
        x: 86.0
        y: 65.0
        z: -46.0
      '6':
        x: 86.0
        y: 64.0
        z: -46.0
      '7':
        x: 87.0
        y: 64.0
        z: -46.0
      '8':
        x: 88.0
        y: 64.0
        z: -46.0
  jaune:
    color: §e
    spawn:
      x: 127.0
      y: 64.0
      z: -80.0
    coffre:
      x: 132.0
      y: 64.0
      z: -77.0
    porte:
      '0':
        x: 122.0
        y: 66.0
        z: -80.0
      '1':
        x: 122.0
        y: 66.0
        z: -81.0
      '2':
        x: 122.0
        y: 66.0
        z: -82.0
      '3':
        x: 122.0
        y: 65.0
        z: -82.0
      '4':
        x: 122.0
        y: 65.0
        z: -81.0
      '5':
        x: 122.0
        y: 65.0
        z: -80.0
      '6':
        x: 122.0
        y: 64.0
        z: -80.0
      '7':
        x: 122.0
        y: 64.0
        z: -81.0
      '8':
        x: 122.0
        y: 64.0
        z: -82.0
  bleu:
    color: §9
    spawn:
      x: 88.0
      y: 64.0
      z: -121.0
    coffre:
      x: 91.0
      y: 64.0
      z: -126.0
    porte:
      '0':
        x: 88.0
        y: 66.0
        z: -116.0
      '1':
        x: 87.0
        y: 66.0
        z: -116.0
      '2':
        x: 86.0
        y: 66.0
        z: -116.0
      '3':
        x: 86.0
        y: 65.0
        z: -116.0
      '4':
        x: 87.0
        y: 65.0
        z: -116.0
      '5':
        x: 88.0
        y: 65.0
        z: -116.0
      '6':
        x: 88.0
        y: 64.0
        z: -116.0
      '7':
        x: 87.0
        y: 64.0
        z: -116.0
      '8':
        x: 86.0
        y: 64.0
        z: -116.0
  vert:
    color: §a
    spawn:
      x: 47.0
      y: 64.0
      z: -82.0
    coffre:
      x: 42.0
      y: 64.0
      z: -85.0
    porte:
      '0':
        x: 52.0
        y: 66.0
        z: -82.0
      '1':
        x: 52.0
        y: 66.0
        z: -81.0
      '2':
        x: 52.0
        y: 66.0
        z: -80.0
      '3':
        x: 52.0
        y: 65.0
        z: -80.0
      '4':
        x: 52.0
        y: 65.0
        z: -81.0
      '5':
        x: 52.0
        y: 65.0
        z: -82.0
      '6':
        x: 52.0
        y: 64.0
        z: -82.0
      '7':
        x: 52.0
        y: 64.0
        z: -81.0
      '8':
        x: 52.0
        y: 64.0
        z: -80.0
npcs:
  '0':
    x: 44.30000001192093
    y: 64.0
    z: -81.30000001192093
    pitch: 6.600013
    yaw: -135.16351
  '1':
    x: 86.69999998807907
    y: 64.0
    z: -37.30000001192093
    pitch: 4.950008
    yaw: -221.25787
  '2':
    x: 130.69999998807907
    y: 64.0
    z: -79.69999998807907
    pitch: 5.5500026
    yaw: -309.15173
  '3':
    x: 88.30000001192093
    y: 64.0
    z: -123.69999998807907
    pitch: 3.7500033
    yaw: -40.351807


settings:
  protected_zone_area_radius: '55'
  mp_set_playzone_radius: '1000'
  arena_safezone_radius: '5'
