name: Create Release for Blog

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'blog/**'

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
  deployments: write

jobs:
  blog_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup utilities
      run: sudo apt-get install zip jq python3 -y && pip install PyGithub && echo "${{ secrets.TOKEN_GITHUB }}" > TOKEN

    - name: Generate new JSON file
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      run: |
        python3 scripts/json_blog.py

    - name: Commit and push blog.json to the repository
      continue-on-error: true
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add blog.json
        git commit -m "Updated blog.json"
        git push origin ${{ github.ref }}
