name: Create Release for Maps

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'maps/**'

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
  deployments: write

jobs:
  maps_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup utilities
      run: sudo apt-get install zip jq python3 -y && pip install PyGithub && echo "${{ secrets.TOKEN_GITHUB }}" > TOKEN

    - name: Compress and archive map folders
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      run: |
        rm -rf zips/
        python3 scripts/zip_maps.py

    - name: Generate new JSON file
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      run: |
        python3 scripts/json_maps.py
    
    - name: Create new releases and move payload file
      env:
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      run: |
        python3 scripts/push_maps.py

    - name: Commit and push maps.json to the repository
      continue-on-error: true
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add maps.json
        git commit -m "Updated maps.json"
        git push origin ${{ github.ref }}
